# Generated by Django 5.2.17 on 2026-09-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0007_reviewcycle_close_check_sent_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewcycle",
            name="include_direct_report",
            field=models.BooleanField(default=True, verbose_name="Direct report review"),
        ),
        migrations.AddField(
            model_name="reviewcycle",
            name="include_manager",
            field=models.BooleanField(default=True, verbose_name="Manager review"),
        ),
        migrations.AddField(
            model_name="reviewcycle",
            name="include_peer",
            field=models.BooleanField(default=True, verbose_name="Peer review"),
        ),
        migrations.AddField(
            model_name="reviewcycle",
            name="include_self",
            field=models.BooleanField(default=True, verbose_name="Self assessment"),
        ),
    ]
